# Generated by Django 5.0.1 on 2024-02-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchpaper",
            name="recommendations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="classification",
            field=models.CharField(
                choices=[(1, "Basic Research"), (2, "Applied Research")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="record_type",
            field=models.CharField(
                choices=[(1, "Proposal"), (2, "Thesis/Research"), (3, "Project")],
                max_length=50,
            ),
        ),
    ]
