# Generated by Django 5.0.1 on 2024-02-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Backend", "0003_alter_researchpaper_recommendations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchpaper",
            name="classification",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="record_type",
            field=models.CharField(max_length=50),
        ),
    ]
