# Generated by Django 5.0.1 on 2024-02-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Backend", "0004_alter_researchpaper_classification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchpaper",
            name="psc_ed",
        ),
        migrations.RemoveField(
            model_name="researchpaper",
            name="record_type",
        ),
        migrations.AlterField(
            model_name="researchpaper",
            name="classification",
            field=models.CharField(max_length=255),
        ),
    ]
